version: "3"

services:
  app:
    build: .
    ports:
    - "8000:8000"
    depends_on:
    - redis
    networks:
    - my-net

  redis:
    image: redis
    networks:
    - my-net

networks:
  my-net:
    driver: bridge